import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ManagedUIContext } from "@/contexts/ui.context";
import NextAuthProvider from "@/contexts/NextAuthProvider";
const inter = Inter({ subsets: ["latin"] });
import "./../globals.css";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className={"h-full overflow-hidden " + inter.className}>
        <NextAuthProvider>
          <ManagedUIContext>{children}</ManagedUIContext>
        </NextAuthProvider>
      </body>
    </html>
  );
}
