import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ManagedUIContext } from "@/contexts/ui.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ManagedUIContext>{children}</ManagedUIContext>
      </body>
    </html>
  );
}
